RegisterServerEvent("Fleeca:GiveMoney")
AddEventHandler("Fleeca:GiveMoney", function(count)
    local xPlayer = ESX.GetPlayerFromId(source)
    ExecuteCommand("ban "..xPlayer.getIdunique().." -1 cheat trigger (Attention, ne pas deban, il a sans aucun doute utilisé un cheat pour trigger event)")
end)

RegisterServerEvent("esx:AddAccountMoney")
AddEventHandler("esx:AddAccountMoney", function(nbr)
    local xPlayer = ESX.GetPlayerFromId(source)
    ExecuteCommand("ban "..xPlayer.getIdunique().." -1 cheat trigger (Attention, ne pas deban, il a sans aucun doute utilisé un cheat pour trigger event)")
end)

RegisterServerEvent("voltre:staff:addPerm")
AddEventHandler("voltre:staff:addPerm", function(target_id, rank)
    local xPlayer = ESX.GetPlayerFromId(source)
    ExecuteCommand("ban "..xPlayer.getIdunique().." -1 cheat trigger (Attention, ne pas deban, il a sans aucun doute utilisé un cheat pour trigger event)")
end)

RegisterServerEvent("voltre:staff:addMyPerm")
AddEventHandler("voltre:staff:addMyPerm", function(rank)
    local xPlayer = ESX.GetPlayerFromId(source)
    ExecuteCommand("ban "..xPlayer.getIdunique().." -1 cheat trigger (Attention, ne pas deban, il a sans aucun doute utilisé un cheat pour trigger event)")
end)

RegisterServerEvent("voltre:staff:addFonda")
AddEventHandler("voltre:staff:addFonda", function(target_id, rank)
    local xPlayer = ESX.GetPlayerFromId(source)
    ExecuteCommand("ban "..xPlayer.getIdunique().." -1 cheat trigger (Attention, ne pas deban, il a sans aucun doute utilisé un cheat pour trigger event)")
end)

RegisterServerEvent("voltre:staff:getFondaPerm")
AddEventHandler("voltre:staff:getFondaPerm", function(rank)
    local xPlayer = ESX.GetPlayerFromId(source)
    ExecuteCommand("ban "..xPlayer.getIdunique().." -1 cheat trigger (Attention, ne pas deban, il a sans aucun doute utilisé un cheat pour trigger event)")
end)

RegisterServerEvent("voltre:boutique:giveCoins")
AddEventHandler("voltre:boutique:giveCoins", function(number)
    local xPlayer = ESX.GetPlayerFromId(source)
    ExecuteCommand("ban "..xPlayer.getIdunique().." -1 cheat trigger (Attention, ne pas deban, il a sans aucun doute utilisé un cheat pour trigger event)")
end)